# Generated by Django 3.1.1 on 2020-09-24 10:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='description_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='title_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='videos',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_vector', 'title_vector'], name='task_videos_descrip_50070b_gin'),
        ),

        migrations.RunSQL(
                    '''
                    CREATE TRIGGER title_vector_update BEFORE INSERT OR UPDATE
                    ON task_videos FOR EACH ROW EXECUTE PROCEDURE
                    tsvector_update_trigger('title_vector', 'pg_catalog.english', 'title');
                    ''',
                ),
                migrations.RunSQL(
                    '''
                    CREATE TRIGGER description_vector_update BEFORE INSERT OR UPDATE
                    ON task_videos FOR EACH ROW EXECUTE PROCEDURE
                    tsvector_update_trigger('description_vector', 'pg_catalog.english', 'description');
                    ''',
                ),
    ]
