# Generated by Django 3.1.1 on 2020-09-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200924_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
